
export const PREDEFINED_TAGS = [
  'UI/UX',
  'Web Dizayn',
  'Mobil Dizayn',
  'Ilova Dizayni',
  'Logotip',
  'Branding',
  'Grafik Dizayn',
  'Illustratsiya',
  '3D Model',
  'Animatsiya',
  'Harakatli Grafika (Motion Graphics)',
  'Art',
  'Ikonka',
  'Brendbuk',
  'Qadoq Dizayni (Packaging)',
  'Shrift (Typography)',
  'Interfeys',
  'Veb-sayt',
  'Landing Page',
  'Promo-sayt',
  'Korporativ Identitet',
  'Plakat (Poster)',
  'Infografika',
  'Oyin Dizayni (Game Design)',
  'Fotografiya',
  'Arxitektura',
  'Interyer Dizayni',
  'Sanoat Dizayni',
  'Kitob Dizayni',
  'Rassomchilik',
] as const;
