import {
  Palette,
  Laptop,
  Smartphone,
  AppWindow,
  PenTool,
  Bot,
  Clapperboard,
  Film,
  Brush,
  Component,
  Boxes,
  Book,
  Printer,
  Building2,
  Camera,
  Paintbrush,
  Car,
  Scroll,
  ShoppingBag,
  Mic,
  Dumbbell,
  LayoutGrid,
  Globe,
  Grid
} from 'lucide-react';
import type { LucideIcon } from 'lucide-react';

export const TAG_VISUALS: Record<string, { icon: LucideIcon; imageUrl: string; }> = {
  'Barchasi': { icon: Grid, imageUrl: 'https://picsum.photos/seed/all/400/300' },
  'UI/UX': { icon: Palette, imageUrl: 'https://picsum.photos/seed/uiux/400/300' },
  'Web Dizayn': { icon: Laptop, imageUrl: 'https://picsum.photos/seed/web/400/300' },
  'Mobil Dizayn': { icon: Smartphone, imageUrl: 'https://picsum.photos/seed/mobile/400/300' },
  'Ilova Dizayni': { icon: AppWindow, imageUrl: 'https://picsum.photos/seed/app/400/300' },
  'Logotip': { icon: PenTool, imageUrl: 'https://picsum.photos/seed/logo/400/300' },
  'Branding': { icon: Bot, imageUrl: 'https://picsum.photos/seed/branding/400/300' },
  'Grafik Dizayn': { icon: Brush, imageUrl: 'https://picsum.photos/seed/graphic/400/300' },
  'Illustratsiya': { icon: Paintbrush, imageUrl: 'https://picsum.photos/seed/illustration/400/300' },
  '3D Model': { icon: Boxes, imageUrl: 'https://picsum.photos/seed/3d/400/300' },
  'Animatsiya': { icon: Film, imageUrl: 'https://picsum.photos/seed/animation/400/300' },
  'Motion Graphics': { icon: Clapperboard, imageUrl: 'https://picsum.photos/seed/motion/400/300' },
  'Art': { icon: Brush, imageUrl: 'https://picsum.photos/seed/art/400/300' },
  'Ikonka': { icon: Component, imageUrl: 'https://picsum.photos/seed/icon/400/300' },
  'Brendbuk': { icon: Book, imageUrl: 'https://picsum.photos/seed/brandbook/400/300' },
  'Packaging': { icon: ShoppingBag, imageUrl: 'https://picsum.photos/seed/packaging/400/300' },
  'Shrift (Typography)': { icon: Scroll, imageUrl: 'https://picsum.photos/seed/typography/400/300' },
  'Interfeys': { icon: LayoutGrid, imageUrl: 'https://picsum.photos/seed/interface/400/300' },
  'Veb-sayt': { icon: Globe, imageUrl: 'https://picsum.photos/seed/website/400/300' },
  'Landing Page': { icon: Laptop, imageUrl: 'https://picsum.photos/seed/landing/400/300' },
  'Promo-sayt': { icon: Globe, imageUrl: 'https://picsum.photos/seed/promo/400/300' },
  'Korporativ Identitet': { icon: Building2, imageUrl: 'https://picsum.photos/seed/corporate/400/300' },
  'Plakat (Poster)': { icon: Printer, imageUrl: 'https://picsum.photos/seed/poster/400/300' },
  'Infografika': { icon: Mic, imageUrl: 'https://picsum.photos/seed/infographic/400/300' },
  'Oyin Dizayni (Game Design)': { icon: Dumbbell, imageUrl: 'https://picsum.photos/seed/game/400/300' },
  'Fotografiya': { icon: Camera, imageUrl: 'https://picsum.photos/seed/photo/400/300' },
  'Arxitektura': { icon: Building2, imageUrl: 'https://picsum.photos/seed/architecture/400/300' },
  'Interyer Dizayni': { icon: Building2, imageUrl: 'https://picsum.photos/seed/interior/400/300' },
  'Sanoat Dizayni': { icon: Car, imageUrl: 'https://picsum.photos/seed/industrial/400/300' },
  'Kitob Dizayni': { icon: Book, imageUrl: 'https://picsum.photos/seed/bookdesign/400/300' },
  'Rassomchilik': { icon: Paintbrush, imageUrl: 'https://picsum.photos/seed/painting/400/300' }
};
